using BusinessOS.Pharmacy.Application.Abstractions.Authentication;using BusinessOS.Pharmacy.Application.Abstractions.DailyClosing;using BusinessOS.Pharmacy.Application.Abstractions.Inventory;using BusinessOS.Pharmacy.Application.Abstractions.Medicines;using BusinessOS.Pharmacy.Application.Abstractions.Persistence;using BusinessOS.Pharmacy.Application.Abstractions.Sales;using BusinessOS.Pharmacy.Domain.Authentication;using BusinessOS.Pharmacy.Infrastructure;using BusinessOS.Pharmacy.Infrastructure.Storage;using BusinessOS.Pharmacy.Persistence;using Microsoft.Data.Sqlite;using Microsoft.Extensions.DependencyInjection;using Xunit;
namespace BusinessOS.Pharmacy.IntegrationTests.Persistence;
public sealed class DailyClosingTests
{
 [Fact]public async Task Snapshot_counts_cash_change_returns_and_opening_cash()
 {
  var root=Tmp();try{await using var p=Build(root);await Init(p);var setup=await Setup(p);var dc=p.GetRequiredService<IDailyClosingService>();await dc.OpenShiftAsync(setup.LocationId,100m);var pos=p.GetRequiredService<IPosService>();var sale=await pos.CheckoutAsync(new PosCheckoutRequest(setup.LocationId,null,"close-sale",null,null,null,null,[new PosCheckoutLineRequest(setup.MedicineId,1m)],[new PosPaymentRequest("cash",120m)]));var ret=p.GetRequiredService<ISaleReturnService>();var line=Assert.Single((await ret.GetReturnableSaleAsync(sale.Sale.Id))!.Lines);await ret.ProcessAsync(new ProcessSaleReturnRequest(sale.Sale.Id,"close-ret","Return",[new ProcessSaleReturnLineRequest(line.Id,0.2m)],[new ProcessSaleReturnRefundRequest("cash",20m)]));var w=await dc.GetWorkspaceAsync(setup.LocationId);Assert.Equal(100m,w.Snapshot.GrossSales);Assert.Equal(20m,w.Snapshot.ReturnsTotal);Assert.Equal(60m,w.Snapshot.CashCollected);Assert.Equal(160m,w.Snapshot.ExpectedCash);}finally{SqliteConnection.ClearAllPools();Del(root);}
 }
 [Fact]public async Task Finalized_day_blocks_sales_and_returns_until_reopened()
 {
  var root=Tmp();try{await using var p=Build(root);await Init(p);var setup=await Setup(p);var dc=p.GetRequiredService<IDailyClosingService>();var shift=await dc.OpenShiftAsync(setup.LocationId,0m);var pos=p.GetRequiredService<IPosService>();var sale=await pos.CheckoutAsync(new PosCheckoutRequest(setup.LocationId,null,"block-sale",null,null,null,null,[new PosCheckoutLineRequest(setup.MedicineId,1m)],[new PosPaymentRequest("cash",100m)]));await dc.CloseShiftAsync(shift.Id,100m,null);var closing=await dc.FinalizeAsync(setup.LocationId,100m,null);await Assert.ThrowsAsync<InvalidOperationException>(()=>pos.CheckoutAsync(new PosCheckoutRequest(setup.LocationId,null,"blocked-new",null,null,null,null,[new PosCheckoutLineRequest(setup.MedicineId,1m)],[new PosPaymentRequest("cash",100m)])));var ret=p.GetRequiredService<ISaleReturnService>();var line=Assert.Single((await ret.GetReturnableSaleAsync(sale.Sale.Id))!.Lines);await Assert.ThrowsAsync<InvalidOperationException>(()=>ret.ProcessAsync(new ProcessSaleReturnRequest(sale.Sale.Id,"blocked-return","After close",[new ProcessSaleReturnLineRequest(line.Id,1m)],[new ProcessSaleReturnRefundRequest("cash",100m)])));await dc.ReopenAsync(closing.Id,"Correction required");var after=await pos.CheckoutAsync(new PosCheckoutRequest(setup.LocationId,null,"after-reopen",null,null,null,null,[new PosCheckoutLineRequest(setup.MedicineId,1m)],[new PosPaymentRequest("cash",100m)]));Assert.Equal("completed",after.Sale.PaymentStatus=="paid"?"completed":"");}finally{SqliteConnection.ClearAllPools();Del(root);}
 }
 private static async Task<(string MedicineId,string LocationId)> Setup(ServiceProvider p){var m=p.GetRequiredService<IMedicineCatalogService>();var id=await m.CreateAsync(new SaveMedicineRequest(null,null,$"DC-{Guid.NewGuid():N}"[..16],null,"Daily Close Medicine",null,null,"tablet","pack","tablet",1m,0m,false,true,true,true,null));var i=p.GetRequiredService<IInventoryService>();await i.EnsureDefaultsAsync();var loc=(await i.GetReferenceDataAsync()).Locations.Single();await i.CreateOpeningStockAsync(new CreateOpeningStockRequest(id,loc.Id,"DC-B",null,new DateOnly(2028,1,1),10m,50m,100m,null));return(id,loc.Id);}
 private static async Task Init(ServiceProvider p)=>await p.GetRequiredService<ILocalDatabaseInitializer>().InitializeAsync("tenant-closing");private static ServiceProvider Build(string root){var s=new ServiceCollection();s.AddBusinessOSInfrastructure(new ApplicationPaths(root));s.AddSingleton<IPermissionAuthorizer>(new Allow());s.AddSingleton<IUserSessionService>(new Session());s.AddBusinessOSPersistence();return s.BuildServiceProvider(true);}private static string Tmp()=>Path.Combine(Path.GetTempPath(),"darmaltoon-closing-tests",Guid.NewGuid().ToString("N"));private static void Del(string r){if(Directory.Exists(r))Directory.Delete(r,true);}private sealed class Allow:IPermissionAuthorizer{public bool HasPermission(string p)=>true;public void Demand(string p){}}
 private sealed class Session:IUserSessionService{private static readonly UserSessionSnapshot S=new("cashier","tenant-closing","a","d","Cashier","c@test.local",new HashSet<string>{"admin"},new HashSet<string>{"pos.sell","returns.manage","inventory.manage","medicines.manage","daily_closing.perform","daily_closing.approve","accounting.manage"},DateTimeOffset.UtcNow.AddMinutes(-1),DateTimeOffset.UtcNow.AddHours(8));public UserSessionSnapshot? Current=>S;public Task<UserSessionSnapshot> LoginAsync(string e,string p,bool a,CancellationToken c=default)=>Task.FromResult(S);public Task<UserSessionSnapshot> RefreshAsync(CancellationToken c=default)=>Task.FromResult(S);public Task LogoutAsync(CancellationToken c=default)=>Task.CompletedTask;}
}
