using BusinessOS.Pharmacy.Persistence;using Microsoft.EntityFrameworkCore.Infrastructure;using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace BusinessOS.Pharmacy.Persistence.Migrations;
[DbContext(typeof(PharmacyDbContext))][Migration("20260930193000_DailyClosing")]
public partial class DailyClosing:Migration
{
 protected override void Up(MigrationBuilder m)
 {
  m.CreateTable("cashier_shifts",t=>new{id=t.Column<string>("TEXT",maxLength:36,nullable:false),stock_location_id=t.Column<string>("TEXT",maxLength:36,nullable:false),user_id=t.Column<string>("TEXT",maxLength:64,nullable:false),business_date=t.Column<DateOnly>("TEXT",nullable:false),status=t.Column<string>("TEXT",maxLength:24,nullable:false),opening_cash=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),expected_cash=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:true),counted_cash=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:true),variance=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:true),opened_at=t.Column<DateTimeOffset>("TEXT",nullable:false),closed_at=t.Column<DateTimeOffset>("TEXT",nullable:true),closing_notes=t.Column<string>("TEXT",maxLength:1000,nullable:true),created_at=t.Column<DateTimeOffset>("TEXT",nullable:false),updated_at=t.Column<DateTimeOffset>("TEXT",nullable:false)},tb=>{tb.PrimaryKey("PK_cashier_shifts",x=>x.id);tb.ForeignKey("FK_cashier_shifts_stock_locations_stock_location_id",x=>x.stock_location_id,"stock_locations","id",onDelete:ReferentialAction.Restrict);});
  m.CreateTable("daily_closings",t=>new{id=t.Column<string>("TEXT",maxLength:36,nullable:false),stock_location_id=t.Column<string>("TEXT",maxLength:36,nullable:false),business_date=t.Column<DateOnly>("TEXT",nullable:false),status=t.Column<string>("TEXT",maxLength:24,nullable:false),gross_sales=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),discount_total=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),returns_total=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),cash_collected=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),bank_collected=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),mobile_collected=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),credit_sales=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),opening_cash=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),expected_cash=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),counted_cash=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:true),variance=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:true),finalized_by=t.Column<string>("TEXT",maxLength:64,nullable:true),approved_by=t.Column<string>("TEXT",maxLength:64,nullable:true),reopened_by=t.Column<string>("TEXT",maxLength:64,nullable:true),finalized_at=t.Column<DateTimeOffset>("TEXT",nullable:true),approved_at=t.Column<DateTimeOffset>("TEXT",nullable:true),reopened_at=t.Column<DateTimeOffset>("TEXT",nullable:true),closing_notes=t.Column<string>("TEXT",maxLength:2000,nullable:true),reopen_reason=t.Column<string>("TEXT",maxLength:2000,nullable:true),created_at=t.Column<DateTimeOffset>("TEXT",nullable:false),updated_at=t.Column<DateTimeOffset>("TEXT",nullable:false)},tb=>{tb.PrimaryKey("PK_daily_closings",x=>x.id);tb.ForeignKey("FK_daily_closings_stock_locations_stock_location_id",x=>x.stock_location_id,"stock_locations","id",onDelete:ReferentialAction.Restrict);});
  m.CreateTable("daily_closing_events",t=>new{id=t.Column<string>("TEXT",maxLength:36,nullable:false),daily_closing_id=t.Column<string>("TEXT",maxLength:36,nullable:false),event_type=t.Column<string>("TEXT",maxLength:40,nullable:false),actor_id=t.Column<string>("TEXT",maxLength:64,nullable:true),reason=t.Column<string>("TEXT",maxLength:2000,nullable:true),snapshot=t.Column<string>("TEXT",nullable:true),occurred_at=t.Column<DateTimeOffset>("TEXT",nullable:false),created_at=t.Column<DateTimeOffset>("TEXT",nullable:false),updated_at=t.Column<DateTimeOffset>("TEXT",nullable:false)},tb=>{tb.PrimaryKey("PK_daily_closing_events",x=>x.id);tb.ForeignKey("FK_daily_closing_events_daily_closings_daily_closing_id",x=>x.daily_closing_id,"daily_closings","id",onDelete:ReferentialAction.Cascade);});
  m.CreateIndex("IX_cashier_shifts_stock_location_id","cashier_shifts","stock_location_id");m.CreateIndex("IX_cashier_shifts_business_date","cashier_shifts","business_date");m.CreateIndex("IX_cashier_shifts_status","cashier_shifts","status");m.CreateIndex("IX_cashier_shifts_opened_at","cashier_shifts","opened_at");m.CreateIndex("IX_cashier_shifts_closed_at","cashier_shifts","closed_at");m.CreateIndex("IX_cashier_shifts_stock_location_id_business_date_status","cashier_shifts",new[]{"stock_location_id","business_date","status"});m.CreateIndex("IX_cashier_shifts_user_id_business_date_status","cashier_shifts",new[]{"user_id","business_date","status"});
  m.CreateIndex("IX_daily_closings_stock_location_id_business_date","daily_closings",new[]{"stock_location_id","business_date"},unique:true);m.CreateIndex("IX_daily_closings_status","daily_closings","status");m.CreateIndex("IX_daily_closings_finalized_at","daily_closings","finalized_at");m.CreateIndex("IX_daily_closings_approved_at","daily_closings","approved_at");m.CreateIndex("IX_daily_closings_reopened_at","daily_closings","reopened_at");
  m.CreateIndex("IX_daily_closing_events_daily_closing_id","daily_closing_events","daily_closing_id");m.CreateIndex("IX_daily_closing_events_event_type","daily_closing_events","event_type");m.CreateIndex("IX_daily_closing_events_occurred_at","daily_closing_events","occurred_at");
 }
 protected override void Down(MigrationBuilder m){m.DropTable("daily_closing_events");m.DropTable("cashier_shifts");m.DropTable("daily_closings");}
}
