using BusinessOS.Pharmacy.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace BusinessOS.Pharmacy.Persistence.Migrations;
[DbContext(typeof(PharmacyDbContext))]
[Migration("20260930190000_AccountingExpenses")]
public partial class AccountingExpenses : Migration
{
    protected override void Up(MigrationBuilder m)
    {
        m.CreateTable("ledger_accounts",t=>new{id=t.Column<string>("TEXT",maxLength:36,nullable:false),parent_id=t.Column<string>("TEXT",maxLength:36,nullable:true),code=t.Column<string>("TEXT",maxLength:32,nullable:false),name=t.Column<string>("TEXT",maxLength:160,nullable:false),type=t.Column<string>("TEXT",maxLength:32,nullable:false),normal_balance=t.Column<string>("TEXT",maxLength:8,nullable:false),system_key=t.Column<string>("TEXT",maxLength:64,nullable:true),currency=t.Column<string>("TEXT",fixedLength:true,maxLength:3,nullable:false),is_system=t.Column<bool>("INTEGER",nullable:false),is_active=t.Column<bool>("INTEGER",nullable:false),description=t.Column<string>("TEXT",maxLength:2000,nullable:true),created_at=t.Column<DateTimeOffset>("TEXT",nullable:false),updated_at=t.Column<DateTimeOffset>("TEXT",nullable:false)},table=>{table.PrimaryKey("PK_ledger_accounts",x=>x.id);table.ForeignKey("FK_ledger_accounts_ledger_accounts_parent_id",x=>x.parent_id,"ledger_accounts","id",onDelete:ReferentialAction.SetNull);});
        m.CreateTable("journal_entries",t=>new{id=t.Column<string>("TEXT",maxLength:36,nullable:false),journal_number=t.Column<string>("TEXT",maxLength:80,nullable:false),business_date=t.Column<DateOnly>("TEXT",nullable:false),occurred_at=t.Column<DateTimeOffset>("TEXT",nullable:false),status=t.Column<string>("TEXT",maxLength:24,nullable:false),currency=t.Column<string>("TEXT",fixedLength:true,maxLength:3,nullable:false),source_type=t.Column<string>("TEXT",maxLength:120,nullable:false),source_id=t.Column<string>("TEXT",maxLength:64,nullable:false),source_event=t.Column<string>("TEXT",maxLength:80,nullable:true),source_number=t.Column<string>("TEXT",maxLength:120,nullable:true),idempotency_key=t.Column<string>("TEXT",maxLength:191,nullable:false),reference=t.Column<string>("TEXT",maxLength:160,nullable:true),description=t.Column<string>("TEXT",maxLength:500,nullable:false),total_debit=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),total_credit=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),posted_by=t.Column<string>("TEXT",maxLength:64,nullable:true),reversal_of_id=t.Column<string>("TEXT",maxLength:36,nullable:true),reversal_reason=t.Column<string>("TEXT",maxLength:2000,nullable:true),posted_at=t.Column<DateTimeOffset>("TEXT",nullable:false),created_at=t.Column<DateTimeOffset>("TEXT",nullable:false),updated_at=t.Column<DateTimeOffset>("TEXT",nullable:false)},table=>{table.PrimaryKey("PK_journal_entries",x=>x.id);table.ForeignKey("FK_journal_entries_journal_entries_reversal_of_id",x=>x.reversal_of_id,"journal_entries","id",onDelete:ReferentialAction.Restrict);});
        m.CreateTable("expenses",t=>new{id=t.Column<string>("TEXT",maxLength:36,nullable:false),expense_number=t.Column<string>("TEXT",maxLength:80,nullable:false),expense_account_id=t.Column<string>("TEXT",maxLength:36,nullable:false),payment_account_id=t.Column<string>("TEXT",maxLength:36,nullable:false),stock_location_id=t.Column<string>("TEXT",maxLength:36,nullable:true),business_date=t.Column<DateOnly>("TEXT",nullable:false),currency=t.Column<string>("TEXT",fixedLength:true,maxLength:3,nullable:false),amount=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),payee=t.Column<string>("TEXT",maxLength:180,nullable:true),reference=t.Column<string>("TEXT",maxLength:160,nullable:true),notes=t.Column<string>("TEXT",maxLength:2000,nullable:true),status=t.Column<string>("TEXT",maxLength:24,nullable:false),idempotency_key=t.Column<string>("TEXT",maxLength:191,nullable:false),created_by=t.Column<string>("TEXT",maxLength:64,nullable:false),posted_at=t.Column<DateTimeOffset>("TEXT",nullable:false),reversed_at=t.Column<DateTimeOffset>("TEXT",nullable:true),created_at=t.Column<DateTimeOffset>("TEXT",nullable:false),updated_at=t.Column<DateTimeOffset>("TEXT",nullable:false)},table=>{table.PrimaryKey("PK_expenses",x=>x.id);table.ForeignKey("FK_expenses_ledger_accounts_expense_account_id",x=>x.expense_account_id,"ledger_accounts","id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_expenses_ledger_accounts_payment_account_id",x=>x.payment_account_id,"ledger_accounts","id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_expenses_stock_locations_stock_location_id",x=>x.stock_location_id,"stock_locations","id",onDelete:ReferentialAction.SetNull);});
        m.CreateTable("journal_lines",t=>new{id=t.Column<string>("TEXT",maxLength:36,nullable:false),journal_entry_id=t.Column<string>("TEXT",maxLength:36,nullable:false),ledger_account_id=t.Column<string>("TEXT",maxLength:36,nullable:false),stock_location_id=t.Column<string>("TEXT",maxLength:36,nullable:true),debit=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),credit=t.Column<decimal>("TEXT",precision:20,scale:4,nullable:false),counterparty_type=t.Column<string>("TEXT",maxLength:80,nullable:true),counterparty_id=t.Column<string>("TEXT",maxLength:64,nullable:true),memo=t.Column<string>("TEXT",maxLength:500,nullable:true),created_at=t.Column<DateTimeOffset>("TEXT",nullable:false),updated_at=t.Column<DateTimeOffset>("TEXT",nullable:false)},table=>{table.PrimaryKey("PK_journal_lines",x=>x.id);table.ForeignKey("FK_journal_lines_journal_entries_journal_entry_id",x=>x.journal_entry_id,"journal_entries","id",onDelete:ReferentialAction.Cascade);table.ForeignKey("FK_journal_lines_ledger_accounts_ledger_account_id",x=>x.ledger_account_id,"ledger_accounts","id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_journal_lines_stock_locations_stock_location_id",x=>x.stock_location_id,"stock_locations","id",onDelete:ReferentialAction.SetNull);});
        foreach(var x in new[]{("IX_ledger_accounts_code","ledger_accounts","code",true),("IX_ledger_accounts_system_key","ledger_accounts","system_key",true),("IX_journal_entries_journal_number","journal_entries","journal_number",true),("IX_journal_entries_idempotency_key","journal_entries","idempotency_key",true),("IX_expenses_expense_number","expenses","expense_number",true),("IX_expenses_idempotency_key","expenses","idempotency_key",true)}) m.CreateIndex(x.Item1,x.Item2,x.Item3,unique:x.Item4);
        m.CreateIndex("IX_ledger_accounts_parent_id","ledger_accounts","parent_id");m.CreateIndex("IX_ledger_accounts_type","ledger_accounts","type");m.CreateIndex("IX_ledger_accounts_is_system","ledger_accounts","is_system");m.CreateIndex("IX_ledger_accounts_is_active","ledger_accounts","is_active");m.CreateIndex("IX_ledger_accounts_type_is_active","ledger_accounts",new[]{"type","is_active"});
        m.CreateIndex("IX_journal_entries_business_date","journal_entries","business_date");m.CreateIndex("IX_journal_entries_occurred_at","journal_entries","occurred_at");m.CreateIndex("IX_journal_entries_status","journal_entries","status");m.CreateIndex("IX_journal_entries_source_type","journal_entries","source_type");m.CreateIndex("IX_journal_entries_source_id","journal_entries","source_id");m.CreateIndex("IX_journal_entries_source_event","journal_entries","source_event");m.CreateIndex("IX_journal_entries_posted_at","journal_entries","posted_at");m.CreateIndex("IX_journal_entries_reversal_of_id","journal_entries","reversal_of_id");m.CreateIndex("IX_journal_entries_source_type_source_id_source_event","journal_entries",new[]{"source_type","source_id","source_event"});m.CreateIndex("IX_journal_entries_business_date_status","journal_entries",new[]{"business_date","status"});
        m.CreateIndex("IX_expenses_expense_account_id","expenses","expense_account_id");m.CreateIndex("IX_expenses_payment_account_id","expenses","payment_account_id");m.CreateIndex("IX_expenses_stock_location_id","expenses","stock_location_id");m.CreateIndex("IX_expenses_business_date","expenses","business_date");m.CreateIndex("IX_expenses_status","expenses","status");m.CreateIndex("IX_expenses_posted_at","expenses","posted_at");m.CreateIndex("IX_expenses_reversed_at","expenses","reversed_at");
        m.CreateIndex("IX_journal_lines_journal_entry_id","journal_lines","journal_entry_id");m.CreateIndex("IX_journal_lines_ledger_account_id_journal_entry_id","journal_lines",new[]{"ledger_account_id","journal_entry_id"});m.CreateIndex("IX_journal_lines_counterparty_type_counterparty_id","journal_lines",new[]{"counterparty_type","counterparty_id"});m.CreateIndex("IX_journal_lines_stock_location_id_ledger_account_id","journal_lines",new[]{"stock_location_id","ledger_account_id"});
    }
    protected override void Down(MigrationBuilder m){m.DropTable("expenses");m.DropTable("journal_lines");m.DropTable("journal_entries");m.DropTable("ledger_accounts");}
}
