// <auto-generated />
using System;
using BusinessOS.Pharmacy.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessOS.Pharmacy.Persistence.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    [Migration("20260929220038_LanUserSessions")]
    partial class LanUserSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.LocalDatabaseIdentityEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DatabaseInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastOpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("local_database_identity", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.LocalLanSessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT")
                        .HasColumnName("permissions_json");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("roles_json");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TerminalId", "ExpiresAt");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("local_lan_sessions", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.LocalLanUserCredentialEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastOnlineVerifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_online_verified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHashBase64")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash_base64");

                    b.Property<int>("PasswordIterations")
                        .HasColumnType("INTEGER")
                        .HasColumnName("password_iterations");

                    b.Property<string>("PasswordSaltBase64")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_salt_base64");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT")
                        .HasColumnName("permissions_json");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("roles_json");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId", "IsActive");

                    b.ToTable("local_lan_user_credentials", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.LocalSequenceEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("local_sequences", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.LocalServerIdentityEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("server_name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("local_server_identity", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.LocalSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("local_settings", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.ManufacturerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("manufacturers", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.MedicineCategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("medicine_categories", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.MedicineEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode")
                        .UseCollation("NOCASE");

                    b.Property<bool>("BatchTrackingRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("batch_tracking_required");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT")
                        .HasColumnName("brand_name")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("dosage_form");

                    b.Property<bool>("ExpiryTrackingRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expiry_tracking_required");

                    b.Property<string>("GenericName")
                        .HasMaxLength(180)
                        .HasColumnType("TEXT")
                        .HasColumnName("generic_name")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("ManufacturerId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("MedicineCategoryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("medicine_category_id");

                    b.Property<string>("MedicineCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("medicine_code")
                        .UseCollation("NOCASE");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<bool>("PrescriptionRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prescription_required");

                    b.Property<string>("PurchaseUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("purchase_unit");

                    b.Property<decimal>("ReorderLevel")
                        .HasPrecision(14, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("reorder_level");

                    b.Property<string>("SaleUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_unit");

                    b.Property<string>("Strength")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("strength");

                    b.Property<decimal>("UnitsPerPurchaseUnit")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("units_per_purchase_unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("BrandName");

                    b.HasIndex("GenericName");

                    b.HasIndex("IsActive");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("MedicineCode")
                        .IsUnique();

                    b.HasIndex("MedicineCategoryId", "IsActive");

                    b.ToTable("medicines", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.NetworkAuditEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.Property<string>("RecordUuid")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("record_uuid");

                    b.Property<string>("RemoteAddress")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_address");

                    b.Property<string>("TerminalId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TerminalId");

                    b.ToTable("network_audit_log", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.RegisteredTerminalEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AllowedPermissionsJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_permissions_json");

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("computer_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("registered_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("secret_hash");

                    b.Property<string>("TerminalRole")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_role");

                    b.HasKey("Id");

                    b.HasIndex("ComputerName");

                    b.HasIndex("IsActive");

                    b.ToTable("registered_terminals", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.TerminalPairingCodeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CodeHashBase64")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("code_hash_base64");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_attempts");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_attempts");

                    b.Property<string>("SaltBase64")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("salt_base64");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("used_at");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("terminal_pairing_codes", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.MedicineEntity", b =>
                {
                    b.HasOne("BusinessOS.Pharmacy.Persistence.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany("Medicines")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BusinessOS.Pharmacy.Persistence.Entities.MedicineCategoryEntity", "Category")
                        .WithMany("Medicines")
                        .HasForeignKey("MedicineCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.MedicineCategoryEntity", b =>
                {
                    b.Navigation("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
