// <auto-generated />
using System;
using BusinessOS.Pharmacy.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessOS.Pharmacy.Persistence.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    partial class PharmacyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.LocalDatabaseIdentityEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DatabaseInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastOpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("local_database_identity", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.LocalSequenceEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("local_sequences", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.LocalSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("local_settings", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.ManufacturerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("manufacturers", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.MedicineCategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("medicine_categories", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.MedicineEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode")
                        .UseCollation("NOCASE");

                    b.Property<bool>("BatchTrackingRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("batch_tracking_required");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT")
                        .HasColumnName("brand_name")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("dosage_form");

                    b.Property<bool>("ExpiryTrackingRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expiry_tracking_required");

                    b.Property<string>("GenericName")
                        .HasMaxLength(180)
                        .HasColumnType("TEXT")
                        .HasColumnName("generic_name")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("ManufacturerId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("MedicineCategoryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("medicine_category_id");

                    b.Property<string>("MedicineCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("medicine_code")
                        .UseCollation("NOCASE");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<bool>("PrescriptionRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prescription_required");

                    b.Property<string>("PurchaseUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("purchase_unit");

                    b.Property<decimal>("ReorderLevel")
                        .HasPrecision(14, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("reorder_level");

                    b.Property<string>("SaleUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_unit");

                    b.Property<string>("Strength")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("strength");

                    b.Property<decimal>("UnitsPerPurchaseUnit")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("units_per_purchase_unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("BrandName");

                    b.HasIndex("GenericName");

                    b.HasIndex("IsActive");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("MedicineCode")
                        .IsUnique();

                    b.HasIndex("MedicineCategoryId", "IsActive");

                    b.ToTable("medicines", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.MedicineEntity", b =>
                {
                    b.HasOne("BusinessOS.Pharmacy.Persistence.Entities.ManufacturerEntity", "Manufacturer")
                        .WithMany("Medicines")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BusinessOS.Pharmacy.Persistence.Entities.MedicineCategoryEntity", "Category")
                        .WithMany("Medicines")
                        .HasForeignKey("MedicineCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("BusinessOS.Pharmacy.Persistence.Entities.MedicineCategoryEntity", b =>
                {
                    b.Navigation("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
